# Generated by Django 3.1.2 on 2021-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='created_by',
            field=models.CharField(default='kashish', max_length=255),
        ),
    ]
