# Generated by Django 3.1.2 on 2021-05-25 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210524_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='me',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.registration'),
        ),
    ]
