# Generated by Django 3.1.2 on 2021-05-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20210525_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='me',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me', to='chat.registration'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='chat.registration'),
        ),
    ]
